spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring-boot-hikaricp-sample
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      validation-timeout: 1000
      minimum-idle: 1
      maximum-pool-size: 1
      connection-timeout: 60000
