# データソースをBean定義する場合はコネクションプールに関する自動設定が行われない。
# そのためコネクションプール設定は任意のプレフィックスにフラットに記述する。
datasource:
  primary:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./resouce;AUTO_SERVER=true
    username: sa
    password:
    type: org.apache.tomcat.jdbc.pool.DataSource
    max-active: 1
  secondary:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./resouce;AUTO_SERVER=true
    username: sa
    password:
    type: org.apache.tomcat.jdbc.pool.DataSource
    max-active: 2
