spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./resouce;AUTO_SERVER=true
    username: sa
    password:
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      min-idle: 1
      max-total: 1
      default-query-timeout: 60000
